### ISSUE TITLE
Add purchases to this

### ISSUE THREAD

**Issue by FoksVHox** [JustPlayerDE/libgmodstore#2]
The title says all :)

**Comment by justinkluever** [comment]
Can you please describe further what you actually mean?
The title does not give enough informations :)

**Comment by FoksVHox** [comment]
Add so I can see my purchases with this..

**Comment by justinkluever** [comment]
This is not possibly as i can only see "when" you purchased an addon and if you revoked it, not the addon informations itself.

This would also add no real feature to the website as you can already see your purchases on Gmodstore itself :)

**Comment by FoksVHox** [comment]
I disagree about the feature thing. Because it would make it possible for me to actually get notified twice about an updated addon.

**Comment by justinkluever** [comment]
even if the api tokens can see your purchases (more than 2 timestamps) a content creator is still required* to register the addon on the website because to get the Versions of that addon i need the api key from the addon creator

and without a privacy problem i cannot implement this into the addon (either everyone gets access to your informations or it will require a ingame login too which is slower as going to gmodstore.com and check your notifications)

*: only exception is when gmodstore is changing their api so that everyone who purchased it can see the versions too (this may not happen tho)

**Comment by FoksVHox** [comment]
I don't see the "privacy issue"

**Comment by justinkluever** [comment]
I'll Closeit here.

I need to save or proccess Customer data (addons you own for example, not just Addons the creator has registered) which is what i try to prevent.

To notify you about the addon updates of addons you own and not just have on your server i need to:

**A**: verify that its you, you need to Authenticate and so its useless because its faster to go to gmodstore.com (you dont need to login because the session cookie in steam may still there in your default browser) which makes it useless

**B**: make your purchases **public** for everyone to see, which may not even allowed in Europe because of GDPR (that data is private on default and most people may have an issue with it)

But the real issue here is still that the Gmodstore API doesnt even expose your purchases, only useless data like "Purchase Date" or "Revoked" (no id or version)
